package com.scott_tigers.oncall.shared;

public class Properties {

    public static final String AGE = "Age";
    public static final String ALL_CAPS_UID = "UID";
    public static final String AREA = "Area";
    public static final String ASSIGNEE = "Assignee";
    public static final String CASE_ID = "Case ID";
    public static final String COMMENTS = "Comments";
    public static final String COMPANY = "Company";
    public static final String COUNT = "Count";
    public static final String CREATE_DATE = "Create Date";
    public static final String CREATED = "Created";
    public static final String CURRENT_TICKETS_PER_WEEK = "Current Tickets Per Week";
    public static final String DATE = "Date";
    public static final String DAYS = "Days";
    public static final String DESCRIPTION = "Description";
    public static final String EMAIL = "Email";
    public static final String END_DATE_1 = "End Date 1";
    public static final String END_DATE_2 = "End Date 2";
    public static final String ESCALATION_BY = "Escalated By";
    public static final String FIRST_NAME = "firstName";
    public static final String ITEM = "Item";
    public static final String LAST_MODIFIED_DATE = "Last Modified Date";
    public static final String LINK = "Link";
    public static final String MONTH = "Month";
    public static final String NAME = "Name";
    public static final String NOTES = "Notes";
    public static final String OPEN = "Open";
    public static final String OWNER = "Owner";
    public static final String RATIONALE = "Rationale";
    public static final String RELEASE = "Release";
    public static final String RELEASE_DATE = "Release Date";
    public static final String RESOLVED = "Resolved";
    public static final String RESOLVED_DATE = "Resolved Date";
    public static final String REVIEW = "Review";
    public static final String ROOT_CAUSE_DETAILS = "Root Cause Details";
    public static final String SDE = "SDE";
    public static final String SEARCH_URL = "Search URL";
    public static final String SIM_OR_ISSUE = "SIM or Issue";
    public static final String START_DATE_1 = "Start Date 1";
    public static final String START_DATE_2 = "Start Date 2";
    public static final String START_DATE_3 = "Start Date 3";
    public static final String STATE = "State";
    public static final String STATUS = "Status";
    public static final String TICKET = "Ticket";
    public static final String TICKET_ID = "Ticket ID";
    public static final String TICKETS = "Tickets";
    public static final String TICKETS_PER_MONTH = "Tickets Per Month";
    public static final String TICKETS_PER_WEEK = "Tickets Per Week";
    public static final String TO = "To";
    public static final String TOTAL_TICKETS = "Total Tickets";
    public static final String TYPE = "Type";
    public static final String UID = "UID";
    public static final String URL = "URL";
    public static final String WEIGHT = "weight";
    public static final String DELTA = "Delta";

}
