package com.scott_tigers.oncall.shared;

public class URL {

    public static final String CIT_ON_CALL_SCHEDULE = "https://oncall.corp.amazon.com/#/view/aurora-head-ams-customer-issues-team/schedule";
    public static final String CIT_RESOLVED_TICKETS = "https://tt.amazon.com/search?category=AWS&type=RDS-AuroraMySQL&item=CustomerIssue&assigned_group=aurora-head%3Baurora-head-trx%3Baurora-head-backlog%3Baurora-head-ecosystem%3Baurora-head-partition%3Baurora-head-qp%3Baurora-head-store%3Baurora-head-secondary-wip%3Boscar-eng-secondary%3Baurora-secondary-RCA%3Baurora-head-serverless&status=Resolved%3BClosed&impact=&assigned_individual=&requester_login=&login_name=&cc_email=&phrase_search_text=&keyword_bq=&exact_bq=&or_bq1=&or_bq2=&or_bq3=&exclude_bq=&create_date=&modified_date=06%2F29%2F2020&tags=&case_type=&building_id=&search=Search%21";
    public static final String CIT_SCHEDULE = "https://quip-amazon.com/bBgzAtgbP5aZ/Customer-Issue-Team-Schedule#bVY9CAncgA8";
    public static final String CIT_TICKET_TRACKER = "https://quip-amazon.com/nhftAqjImkQT/Customer-Issues-Ticket-Tracker";
    public static final String CIT_UNAVAILABILITY = "https://quip-amazon.com/YDe3AxS94B4g/Customer-Issue-Team-Unavailability#bbH9CAJefJa";
    public static final String COMPONENT_LABELS = "https://quip-amazon.com/WScHAveNOQlM/Organization#VFV9CAFs1RY";
    public static final String ESCALATED_TICKETS = "https://tt.amazon.com/search?category=AWS&type=RDS-AuroraMySQL&item=CustomerIssue&assigned_group=aurora-head%3Baurora-head-trx%3Baurora-head-backlog%3Baurora-head-ecosystem%3Baurora-head-partition%3Baurora-head-qp%3Baurora-head-store%3Baurora-head-secondary-wip%3Boscar-eng-secondary%3Baurora-secondary-RCA%3Baurora-head-serverless&status=Assigned%3BResearching%3BWork+In+Progress%3BPending%3BResolved%3BClosed&impact=&assigned_individual=&requester_login=&login_name=&cc_email=&phrase_search_text=&keyword_bq=&exact_bq=&or_bq1=&or_bq2=&or_bq3=&exclude_bq=&create_date=&modified_date=&tags=&case_type=&building_id=&short_description=ESCALATION%5D&search=Search%21";
    public static final String LTTR_CANDIDATES = "https://quip-amazon.com/t1vOAeHIrDz4/LTTR-Candidates#dAL9CA8W4pZ";
    public static final String LTTR_PLAN = "https://quip-amazon.com/y0u0AGabkbFr/Aurora-MySQL-2020-LTTR-Plan";
    public static final String OPEN_CUSTOMER_ISSUE_TICKETS = "https://tt.amazon.com/search?category=AWS&type=RDS-AuroraMySQL&item=CustomerIssue&assigned_group=aurora-head%3Baurora-head-trx%3Baurora-head-backlog%3Baurora-head-ecosystem%3Baurora-head-partition%3Baurora-head-qp%3Baurora-head-store%3Baurora-head-secondary-wip%3Boscar-eng-secondary%3Baurora-secondary-RCA%3Baurora-head-serverless&status=Assigned%3BResearching%3BWork+In+Progress%3BPending&impact=&assigned_individual=&requester_login=&login_name=&cc_email=&phrase_search_text=&keyword_bq=&exact_bq=&or_bq1=&or_bq2=&or_bq3=&exclude_bq=&create_date=&modified_date=&tags=&case_type=&building_id=&search=Search%21";
    public static final String RECENT_OPEN_CUSTOMER_ISSUE_SEARCH = "https://tt.amazon.com/search?category=AWS&type=RDS-AuroraMySQL&item=CustomerIssue&assigned_group=aurora-head%3Baurora-head-trx%3Baurora-head-backlog%3Baurora-head-ecosystem%3Baurora-head-partition%3Baurora-head-qp%3Baurora-head-store%3Baurora-head-secondary-wip%3Boscar-eng-secondary%3Baurora-secondary-RCA%3Baurora-head-serverless&status=Assigned%3BResearching%3BWork+In+Progress%3BPending&impact=&assigned_individual=&requester_login=&login_name=&cc_email=&phrase_search_text=&keyword_bq=&exact_bq=&or_bq1=&or_bq2=&or_bq3=&exclude_bq=&create_date=&modified_date=&tags=&case_type=&building_id=&search=Search%21";
    public static final String TICKET_ESCALATIONS = "https://quip-amazon.com/tldaAJ31Ik7Y/Ticket-Escalations";
    public static final String TT_URL_PREFIX = "https://tt.amazon.com/";
}
